
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.minecraftalphaargmod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.minecraftalphaargmod.item.VoidKeyItem;
import net.mcreator.minecraftalphaargmod.item.VoidGemItem;
import net.mcreator.minecraftalphaargmod.item.UnusedToolItem;
import net.mcreator.minecraftalphaargmod.item.UnusedTool9Item;
import net.mcreator.minecraftalphaargmod.item.UnusedTool8Item;
import net.mcreator.minecraftalphaargmod.item.UnusedTool7Item;
import net.mcreator.minecraftalphaargmod.item.UnusedTool6Item;
import net.mcreator.minecraftalphaargmod.item.UnusedTool5Item;
import net.mcreator.minecraftalphaargmod.item.UnusedTool4Item;
import net.mcreator.minecraftalphaargmod.item.UnusedTool3Item;
import net.mcreator.minecraftalphaargmod.item.UnusedTool2Item;
import net.mcreator.minecraftalphaargmod.item.UnusedTool1Item;
import net.mcreator.minecraftalphaargmod.item.UnusedTool11Item;
import net.mcreator.minecraftalphaargmod.item.UnusedTool10Item;
import net.mcreator.minecraftalphaargmod.item.UnusedItemItem;
import net.mcreator.minecraftalphaargmod.item.UnusedItem9Item;
import net.mcreator.minecraftalphaargmod.item.UnusedItem8Item;
import net.mcreator.minecraftalphaargmod.item.UnusedItem7Item;
import net.mcreator.minecraftalphaargmod.item.UnusedItem6Item;
import net.mcreator.minecraftalphaargmod.item.UnusedItem5Item;
import net.mcreator.minecraftalphaargmod.item.UnusedItem4Item;
import net.mcreator.minecraftalphaargmod.item.UnusedItem3Item;
import net.mcreator.minecraftalphaargmod.item.UnusedItem2Item;
import net.mcreator.minecraftalphaargmod.item.UnusedItem1Item;
import net.mcreator.minecraftalphaargmod.item.UnusedItem10Item;
import net.mcreator.minecraftalphaargmod.item.TheOneTrueBookItem;
import net.mcreator.minecraftalphaargmod.item.TeaLeafItem;
import net.mcreator.minecraftalphaargmod.item.TeaBucketItem;
import net.mcreator.minecraftalphaargmod.item.SunglassesItem;
import net.mcreator.minecraftalphaargmod.item.StylisharmorItem;
import net.mcreator.minecraftalphaargmod.item.SpearItem;
import net.mcreator.minecraftalphaargmod.item.ServerDriveItem;
import net.mcreator.minecraftalphaargmod.item.ScytheItem;
import net.mcreator.minecraftalphaargmod.item.SandcastlesItem;
import net.mcreator.minecraftalphaargmod.item.RubyItem;
import net.mcreator.minecraftalphaargmod.item.RockBeetleItem;
import net.mcreator.minecraftalphaargmod.item.RainConchItem;
import net.mcreator.minecraftalphaargmod.item.RaggedArmorItem;
import net.mcreator.minecraftalphaargmod.item.QuestMenagerItem;
import net.mcreator.minecraftalphaargmod.item.PyriteItem;
import net.mcreator.minecraftalphaargmod.item.PearItem;
import net.mcreator.minecraftalphaargmod.item.ObsidianPearItem;
import net.mcreator.minecraftalphaargmod.item.ObsidianIngotItem;
import net.mcreator.minecraftalphaargmod.item.ObsidianArmorItem;
import net.mcreator.minecraftalphaargmod.item.ObserverFurItem;
import net.mcreator.minecraftalphaargmod.item.NoiseSupItem;
import net.mcreator.minecraftalphaargmod.item.MyconToolSetSwordItem;
import net.mcreator.minecraftalphaargmod.item.MyconToolSetShovelItem;
import net.mcreator.minecraftalphaargmod.item.MyconToolSetPickaxeItem;
import net.mcreator.minecraftalphaargmod.item.MyconToolSetHoeItem;
import net.mcreator.minecraftalphaargmod.item.MyconToolSetAxeItem;
import net.mcreator.minecraftalphaargmod.item.MyconStrandItem;
import net.mcreator.minecraftalphaargmod.item.MalachiteItem;
import net.mcreator.minecraftalphaargmod.item.LemuriaItem;
import net.mcreator.minecraftalphaargmod.item.LaceAgateItem;
import net.mcreator.minecraftalphaargmod.item.KeycardItem;
import net.mcreator.minecraftalphaargmod.item.KeyDJItem;
import net.mcreator.minecraftalphaargmod.item.K2Item;
import net.mcreator.minecraftalphaargmod.item.JumpgradeItem;
import net.mcreator.minecraftalphaargmod.item.JuhryItem;
import net.mcreator.minecraftalphaargmod.item.HoursLongPastIVItem;
import net.mcreator.minecraftalphaargmod.item.HoursLongPastIItem;
import net.mcreator.minecraftalphaargmod.item.HoursLongPastIIItem;
import net.mcreator.minecraftalphaargmod.item.HoursLongPastIIIItem;
import net.mcreator.minecraftalphaargmod.item.HiddendenItem;
import net.mcreator.minecraftalphaargmod.item.HearthenMirrorItem;
import net.mcreator.minecraftalphaargmod.item.GyldanSverdItem;
import net.mcreator.minecraftalphaargmod.item.GrayGunItem;
import net.mcreator.minecraftalphaargmod.item.GranularSaltItem;
import net.mcreator.minecraftalphaargmod.item.FryshroomItem;
import net.mcreator.minecraftalphaargmod.item.FrigidBitsItem;
import net.mcreator.minecraftalphaargmod.item.FlamebergeItem;
import net.mcreator.minecraftalphaargmod.item.ExchangerItem;
import net.mcreator.minecraftalphaargmod.item.EssenceRifleItem;
import net.mcreator.minecraftalphaargmod.item.EssenceItem;
import net.mcreator.minecraftalphaargmod.item.EraserItem;
import net.mcreator.minecraftalphaargmod.item.EdibleFireItem;
import net.mcreator.minecraftalphaargmod.item.DownbeatUplinkItem;
import net.mcreator.minecraftalphaargmod.item.DismantlerItem;
import net.mcreator.minecraftalphaargmod.item.DevPromoItem;
import net.mcreator.minecraftalphaargmod.item.DesambrierItem;
import net.mcreator.minecraftalphaargmod.item.CondemnedItem;
import net.mcreator.minecraftalphaargmod.item.ClinohumiteItem;
import net.mcreator.minecraftalphaargmod.item.CatThemeItem;
import net.mcreator.minecraftalphaargmod.item.CandyIceItem;
import net.mcreator.minecraftalphaargmod.item.BismuthIngotItem;
import net.mcreator.minecraftalphaargmod.item.AssetstilesdenyItem;
import net.mcreator.minecraftalphaargmod.item.AssetstilesacceptItem;
import net.mcreator.minecraftalphaargmod.item.ArrivalItem;
import net.mcreator.minecraftalphaargmod.MinecraftAlphaArgModMod;

public class MinecraftAlphaArgModModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MinecraftAlphaArgModMod.MODID);
	public static final RegistryObject<Item> TEA_BUSH = block(MinecraftAlphaArgModModBlocks.TEA_BUSH);
	public static final RegistryObject<Item> TEA_WOOD = block(MinecraftAlphaArgModModBlocks.TEA_WOOD);
	public static final RegistryObject<Item> TEA_PLANKS = block(MinecraftAlphaArgModModBlocks.TEA_PLANKS);
	public static final RegistryObject<Item> TEA_PILLAR = block(MinecraftAlphaArgModModBlocks.TEA_PILLAR);
	public static final RegistryObject<Item> TEEDOOR = doubleBlock(MinecraftAlphaArgModModBlocks.TEEDOOR);
	public static final RegistryObject<Item> FAKEDIRT = block(MinecraftAlphaArgModModBlocks.FAKEDIRT);
	public static final RegistryObject<Item> FAKE_GRASS = block(MinecraftAlphaArgModModBlocks.FAKE_GRASS);
	public static final RegistryObject<Item> WATER_LILY = block(MinecraftAlphaArgModModBlocks.WATER_LILY);
	public static final RegistryObject<Item> TEA_WORKBENCH = block(MinecraftAlphaArgModModBlocks.TEA_WORKBENCH);
	public static final RegistryObject<Item> CELESTIAL_FLAME = block(MinecraftAlphaArgModModBlocks.CELESTIAL_FLAME);
	public static final RegistryObject<Item> DIMENSION_WALL = block(MinecraftAlphaArgModModBlocks.DIMENSION_WALL);
	public static final RegistryObject<Item> DIMENSION_FLOOR = block(MinecraftAlphaArgModModBlocks.DIMENSION_FLOOR);
	public static final RegistryObject<Item> BLUE_DIMENSION_TILE = block(MinecraftAlphaArgModModBlocks.BLUE_DIMENSION_TILE);
	public static final RegistryObject<Item> YELLOW_DIMENSION_TILE = block(MinecraftAlphaArgModModBlocks.YELLOW_DIMENSION_TILE);
	public static final RegistryObject<Item> BISMUTH_BLOCK = block(MinecraftAlphaArgModModBlocks.BISMUTH_BLOCK);
	public static final RegistryObject<Item> BISMUTH_PILLAR = block(MinecraftAlphaArgModModBlocks.BISMUTH_PILLAR);
	public static final RegistryObject<Item> BISMUTH_BRICK = block(MinecraftAlphaArgModModBlocks.BISMUTH_BRICK);
	public static final RegistryObject<Item> FLAMEWOOD = block(MinecraftAlphaArgModModBlocks.FLAMEWOOD);
	public static final RegistryObject<Item> DLAMEWOOD_LEAVES = block(MinecraftAlphaArgModModBlocks.DLAMEWOOD_LEAVES);
	public static final RegistryObject<Item> FLAMEWOOD_PLANKS = block(MinecraftAlphaArgModModBlocks.FLAMEWOOD_PLANKS);
	public static final RegistryObject<Item> TILE = block(MinecraftAlphaArgModModBlocks.TILE);
	public static final RegistryObject<Item> STONE_TILE = block(MinecraftAlphaArgModModBlocks.STONE_TILE);
	public static final RegistryObject<Item> FRIGID_LEAVES = block(MinecraftAlphaArgModModBlocks.FRIGID_LEAVES);
	public static final RegistryObject<Item> FRIGID_TRUNK = block(MinecraftAlphaArgModModBlocks.FRIGID_TRUNK);
	public static final RegistryObject<Item> SALT_BLOCK = block(MinecraftAlphaArgModModBlocks.SALT_BLOCK);
	public static final RegistryObject<Item> SALT_BRICKS = block(MinecraftAlphaArgModModBlocks.SALT_BRICKS);
	public static final RegistryObject<Item> GRANULAR_SALT = REGISTRY.register("granular_salt", () -> new GranularSaltItem());
	public static final RegistryObject<Item> ALTERNATIVE_DIMENSION_WALL = block(MinecraftAlphaArgModModBlocks.ALTERNATIVE_DIMENSION_WALL);
	public static final RegistryObject<Item> OBSIDIAN_INGOT = REGISTRY.register("obsidian_ingot", () -> new ObsidianIngotItem());
	public static final RegistryObject<Item> GRASS_PATHWAY = block(MinecraftAlphaArgModModBlocks.GRASS_PATHWAY);
	public static final RegistryObject<Item> LACE_AGATE_BLOCK = block(MinecraftAlphaArgModModBlocks.LACE_AGATE_BLOCK);
	public static final RegistryObject<Item> MALACHITE_BLOCK = block(MinecraftAlphaArgModModBlocks.MALACHITE_BLOCK);
	public static final RegistryObject<Item> PYRITE_BLOCK = block(MinecraftAlphaArgModModBlocks.PYRITE_BLOCK);
	public static final RegistryObject<Item> CLINOHUMITE_BLOCK = block(MinecraftAlphaArgModModBlocks.CLINOHUMITE_BLOCK);
	public static final RegistryObject<Item> LOW_RIVER_STONE = block(MinecraftAlphaArgModModBlocks.LOW_RIVER_STONE);
	public static final RegistryObject<Item> LOW_RIVERBED = block(MinecraftAlphaArgModModBlocks.LOW_RIVERBED);
	public static final RegistryObject<Item> SNOW_BRICK = block(MinecraftAlphaArgModModBlocks.SNOW_BRICK);
	public static final RegistryObject<Item> GREENSTONE_BRICK = block(MinecraftAlphaArgModModBlocks.GREENSTONE_BRICK);
	public static final RegistryObject<Item> COAL_BRICK = block(MinecraftAlphaArgModModBlocks.COAL_BRICK);
	public static final RegistryObject<Item> MYCON_PILLAR = block(MinecraftAlphaArgModModBlocks.MYCON_PILLAR);
	public static final RegistryObject<Item> MYCON_CAP = block(MinecraftAlphaArgModModBlocks.MYCON_CAP);
	public static final RegistryObject<Item> GLOWING_MYCON_CAP = block(MinecraftAlphaArgModModBlocks.GLOWING_MYCON_CAP);
	public static final RegistryObject<Item> MYCON_PLANK = block(MinecraftAlphaArgModModBlocks.MYCON_PLANK);
	public static final RegistryObject<Item> MYCON_STEM = block(MinecraftAlphaArgModModBlocks.MYCON_STEM);
	public static final RegistryObject<Item> LOW_MYCON = block(MinecraftAlphaArgModModBlocks.LOW_MYCON);
	public static final RegistryObject<Item> MYCON_DOOR = doubleBlock(MinecraftAlphaArgModModBlocks.MYCON_DOOR);
	public static final RegistryObject<Item> FERN = block(MinecraftAlphaArgModModBlocks.FERN);
	public static final RegistryObject<Item> UNKNOWN_1 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_1);
	public static final RegistryObject<Item> ELDERSTONE = block(MinecraftAlphaArgModModBlocks.ELDERSTONE);
	public static final RegistryObject<Item> ELDER_PILLAR = block(MinecraftAlphaArgModModBlocks.ELDER_PILLAR);
	public static final RegistryObject<Item> ELDER_BRICK = block(MinecraftAlphaArgModModBlocks.ELDER_BRICK);
	public static final RegistryObject<Item> ELDER_DECORATED_STONE = block(MinecraftAlphaArgModModBlocks.ELDER_DECORATED_STONE);
	public static final RegistryObject<Item> GOLD_BRICK = block(MinecraftAlphaArgModModBlocks.GOLD_BRICK);
	public static final RegistryObject<Item> DIAMOND_BRICK = block(MinecraftAlphaArgModModBlocks.DIAMOND_BRICK);
	public static final RegistryObject<Item> IRON_BRICK = block(MinecraftAlphaArgModModBlocks.IRON_BRICK);
	public static final RegistryObject<Item> ELDER_SMOOTH_STONE = block(MinecraftAlphaArgModModBlocks.ELDER_SMOOTH_STONE);
	public static final RegistryObject<Item> SLATE_BRICKS = block(MinecraftAlphaArgModModBlocks.SLATE_BRICKS);
	public static final RegistryObject<Item> LICHEN_BRICKS = block(MinecraftAlphaArgModModBlocks.LICHEN_BRICKS);
	public static final RegistryObject<Item> HIGHWOOD_PILLAR = block(MinecraftAlphaArgModModBlocks.HIGHWOOD_PILLAR);
	public static final RegistryObject<Item> FLAMEWOOD_PILLAR = block(MinecraftAlphaArgModModBlocks.FLAMEWOOD_PILLAR);
	public static final RegistryObject<Item> SLATE_BEACON = block(MinecraftAlphaArgModModBlocks.SLATE_BEACON);
	public static final RegistryObject<Item> SLATE_PILLAR = block(MinecraftAlphaArgModModBlocks.SLATE_PILLAR);
	public static final RegistryObject<Item> HEATER = block(MinecraftAlphaArgModModBlocks.HEATER);
	public static final RegistryObject<Item> WIREFRAME_BLOCK = block(MinecraftAlphaArgModModBlocks.WIREFRAME_BLOCK);
	public static final RegistryObject<Item> MYCON_WORKBENCH = block(MinecraftAlphaArgModModBlocks.MYCON_WORKBENCH);
	public static final RegistryObject<Item> FAKE_STONE = block(MinecraftAlphaArgModModBlocks.FAKE_STONE);
	public static final RegistryObject<Item> GREEN_MOJANG_BLOCK = block(MinecraftAlphaArgModModBlocks.GREEN_MOJANG_BLOCK);
	public static final RegistryObject<Item> WHITE_MOJANG_BLOCK = block(MinecraftAlphaArgModModBlocks.WHITE_MOJANG_BLOCK);
	public static final RegistryObject<Item> BLUE_MOJANG_BLOCK = block(MinecraftAlphaArgModModBlocks.BLUE_MOJANG_BLOCK);
	public static final RegistryObject<Item> PILLAR = block(MinecraftAlphaArgModModBlocks.PILLAR);
	public static final RegistryObject<Item> BISMUTH_ORE = block(MinecraftAlphaArgModModBlocks.BISMUTH_ORE);
	public static final RegistryObject<Item> FREEZER = block(MinecraftAlphaArgModModBlocks.FREEZER);
	public static final RegistryObject<Item> FIREWOOD_WORKBENCH = block(MinecraftAlphaArgModModBlocks.FIREWOOD_WORKBENCH);
	public static final RegistryObject<Item> HIGHWOOD_WORKBENCH = block(MinecraftAlphaArgModModBlocks.HIGHWOOD_WORKBENCH);
	public static final RegistryObject<Item> OBSIDIAN_BRICK = block(MinecraftAlphaArgModModBlocks.OBSIDIAN_BRICK);
	public static final RegistryObject<Item> ESSENCE_CACHE = block(MinecraftAlphaArgModModBlocks.ESSENCE_CACHE);
	public static final RegistryObject<Item> DECORATIVE_BLOCK_1 = block(MinecraftAlphaArgModModBlocks.DECORATIVE_BLOCK_1);
	public static final RegistryObject<Item> DECORATIVE_BLOCK_2 = block(MinecraftAlphaArgModModBlocks.DECORATIVE_BLOCK_2);
	public static final RegistryObject<Item> SKY_FLAME_IN_GLASS = block(MinecraftAlphaArgModModBlocks.SKY_FLAME_IN_GLASS);
	public static final RegistryObject<Item> LOW_FLAME_IN_GLASS = block(MinecraftAlphaArgModModBlocks.LOW_FLAME_IN_GLASS);
	public static final RegistryObject<Item> GOLD_FLAME_IN_GLASS = block(MinecraftAlphaArgModModBlocks.GOLD_FLAME_IN_GLASS);
	public static final RegistryObject<Item> OBSIDIAN_FLAME_IN_GLASS = block(MinecraftAlphaArgModModBlocks.OBSIDIAN_FLAME_IN_GLASS);
	public static final RegistryObject<Item> GOLD_ELDER_BRICK = block(MinecraftAlphaArgModModBlocks.GOLD_ELDER_BRICK);
	public static final RegistryObject<Item> LICHEN_MASS = block(MinecraftAlphaArgModModBlocks.LICHEN_MASS);
	public static final RegistryObject<Item> LICHEN = block(MinecraftAlphaArgModModBlocks.LICHEN);
	public static final RegistryObject<Item> HIGHWOOD_LEAVES = block(MinecraftAlphaArgModModBlocks.HIGHWOOD_LEAVES);
	public static final RegistryObject<Item> HIGHWOOD_LOG = block(MinecraftAlphaArgModModBlocks.HIGHWOOD_LOG);
	public static final RegistryObject<Item> HIGHWOOD_PLANKS = block(MinecraftAlphaArgModModBlocks.HIGHWOOD_PLANKS);
	public static final RegistryObject<Item> HIGHWOOD_ROOTS = block(MinecraftAlphaArgModModBlocks.HIGHWOOD_ROOTS);
	public static final RegistryObject<Item> CRUDE_PILLAR = block(MinecraftAlphaArgModModBlocks.CRUDE_PILLAR);
	public static final RegistryObject<Item> SMOOTH_STONE = block(MinecraftAlphaArgModModBlocks.SMOOTH_STONE);
	public static final RegistryObject<Item> SMOOTH_LIMESTONE = block(MinecraftAlphaArgModModBlocks.SMOOTH_LIMESTONE);
	public static final RegistryObject<Item> ESSENCE_TRANSFORMER = block(MinecraftAlphaArgModModBlocks.ESSENCE_TRANSFORMER);
	public static final RegistryObject<Item> ESSENCE_CLONER = block(MinecraftAlphaArgModModBlocks.ESSENCE_CLONER);
	public static final RegistryObject<Item> GREEN_DIMENSION_FLOOR = block(MinecraftAlphaArgModModBlocks.GREEN_DIMENSION_FLOOR);
	public static final RegistryObject<Item> LIMESTONE = block(MinecraftAlphaArgModModBlocks.LIMESTONE);
	public static final RegistryObject<Item> COBBLED_LIMESTONE = block(MinecraftAlphaArgModModBlocks.COBBLED_LIMESTONE);
	public static final RegistryObject<Item> HIGHWOOD_DOOR = doubleBlock(MinecraftAlphaArgModModBlocks.HIGHWOOD_DOOR);
	public static final RegistryObject<Item> FAKE_SAND = block(MinecraftAlphaArgModModBlocks.FAKE_SAND);
	public static final RegistryObject<Item> ICE_DOOR = doubleBlock(MinecraftAlphaArgModModBlocks.ICE_DOOR);
	public static final RegistryObject<Item> FIREWOOD_DOOR = doubleBlock(MinecraftAlphaArgModModBlocks.FIREWOOD_DOOR);
	public static final RegistryObject<Item> FORTIFIED_GLASS = block(MinecraftAlphaArgModModBlocks.FORTIFIED_GLASS);
	public static final RegistryObject<Item> FORTIFIED_BLUE_GLASS = block(MinecraftAlphaArgModModBlocks.FORTIFIED_BLUE_GLASS);
	public static final RegistryObject<Item> FORTIFIED_GREEN_GLASS = block(MinecraftAlphaArgModModBlocks.FORTIFIED_GREEN_GLASS);
	public static final RegistryObject<Item> FORTIFIED_MAGENTA_GLASS = block(MinecraftAlphaArgModModBlocks.FORTIFIED_MAGENTA_GLASS);
	public static final RegistryObject<Item> FORTIFIED_BLACK_GLASS = block(MinecraftAlphaArgModModBlocks.FORTIFIED_BLACK_GLASS);
	public static final RegistryObject<Item> LOW_WART = block(MinecraftAlphaArgModModBlocks.LOW_WART);
	public static final RegistryObject<Item> LOW_WINE = block(MinecraftAlphaArgModModBlocks.LOW_WINE);
	public static final RegistryObject<Item> LOW_LILI = block(MinecraftAlphaArgModModBlocks.LOW_LILI);
	public static final RegistryObject<Item> FLAME_INFUSED_LILY = block(MinecraftAlphaArgModModBlocks.FLAME_INFUSED_LILY);
	public static final RegistryObject<Item> GOLD_INFUSED_LILY = block(MinecraftAlphaArgModModBlocks.GOLD_INFUSED_LILY);
	public static final RegistryObject<Item> OBSIDIAN_INFUSED_LILY = block(MinecraftAlphaArgModModBlocks.OBSIDIAN_INFUSED_LILY);
	public static final RegistryObject<Item> MALACHITE_ORE = block(MinecraftAlphaArgModModBlocks.MALACHITE_ORE);
	public static final RegistryObject<Item> PYRITE_ORE = block(MinecraftAlphaArgModModBlocks.PYRITE_ORE);
	public static final RegistryObject<Item> CLINOHUMITE_ORE = block(MinecraftAlphaArgModModBlocks.CLINOHUMITE_ORE);
	public static final RegistryObject<Item> LACE_AGATE_ORE = block(MinecraftAlphaArgModModBlocks.LACE_AGATE_ORE);
	public static final RegistryObject<Item> HYDRANGEA = block(MinecraftAlphaArgModModBlocks.HYDRANGEA);
	public static final RegistryObject<Item> ROSE = block(MinecraftAlphaArgModModBlocks.ROSE);
	public static final RegistryObject<Item> DANDELION = block(MinecraftAlphaArgModModBlocks.DANDELION);
	public static final RegistryObject<Item> MIXED_GRASS_BLOCK = block(MinecraftAlphaArgModModBlocks.MIXED_GRASS_BLOCK);
	public static final RegistryObject<Item> YELLOW_GRASS_BLOCK = block(MinecraftAlphaArgModModBlocks.YELLOW_GRASS_BLOCK);
	public static final RegistryObject<Item> SAFE = block(MinecraftAlphaArgModModBlocks.SAFE);
	public static final RegistryObject<Item> BISMUTH_INGOT = REGISTRY.register("bismuth_ingot", () -> new BismuthIngotItem());
	public static final RegistryObject<Item> BRICKS = block(MinecraftAlphaArgModModBlocks.BRICKS);
	public static final RegistryObject<Item> HEARTHEN_MIRROR = REGISTRY.register("hearthen_mirror", () -> new HearthenMirrorItem());
	public static final RegistryObject<Item> LICHEN_COBBLESTONE = block(MinecraftAlphaArgModModBlocks.LICHEN_COBBLESTONE);
	public static final RegistryObject<Item> STONE = block(MinecraftAlphaArgModModBlocks.STONE);
	public static final RegistryObject<Item> MYCON_STRAND = REGISTRY.register("mycon_strand", () -> new MyconStrandItem());
	public static final RegistryObject<Item> CLINOHUMITE = REGISTRY.register("clinohumite", () -> new ClinohumiteItem());
	public static final RegistryObject<Item> TEA_LEAF = REGISTRY.register("tea_leaf", () -> new TeaLeafItem());
	public static final RegistryObject<Item> TEA_BUCKET = REGISTRY.register("tea_bucket", () -> new TeaBucketItem());
	public static final RegistryObject<Item> PYRITE = REGISTRY.register("pyrite", () -> new PyriteItem());
	public static final RegistryObject<Item> MALACHITE = REGISTRY.register("malachite", () -> new MalachiteItem());
	public static final RegistryObject<Item> LACE_AGATE = REGISTRY.register("lace_agate", () -> new LaceAgateItem());
	public static final RegistryObject<Item> MYCON_TOOL_SET_PICKAXE = REGISTRY.register("mycon_tool_set_pickaxe", () -> new MyconToolSetPickaxeItem());
	public static final RegistryObject<Item> MYCON_TOOL_SET_AXE = REGISTRY.register("mycon_tool_set_axe", () -> new MyconToolSetAxeItem());
	public static final RegistryObject<Item> MYCON_TOOL_SET_SWORD = REGISTRY.register("mycon_tool_set_sword", () -> new MyconToolSetSwordItem());
	public static final RegistryObject<Item> MYCON_TOOL_SET_SHOVEL = REGISTRY.register("mycon_tool_set_shovel", () -> new MyconToolSetShovelItem());
	public static final RegistryObject<Item> MYCON_TOOL_SET_HOE = REGISTRY.register("mycon_tool_set_hoe", () -> new MyconToolSetHoeItem());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_HELMET = REGISTRY.register("obsidian_armor_helmet", () -> new ObsidianArmorItem.Helmet());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_CHESTPLATE = REGISTRY.register("obsidian_armor_chestplate", () -> new ObsidianArmorItem.Chestplate());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_LEGGINGS = REGISTRY.register("obsidian_armor_leggings", () -> new ObsidianArmorItem.Leggings());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_BOOTS = REGISTRY.register("obsidian_armor_boots", () -> new ObsidianArmorItem.Boots());
	public static final RegistryObject<Item> OBSERVER_FUR = REGISTRY.register("observer_fur", () -> new ObserverFurItem());
	public static final RegistryObject<Item> RAGGED_ARMOR_HELMET = REGISTRY.register("ragged_armor_helmet", () -> new RaggedArmorItem.Helmet());
	public static final RegistryObject<Item> RAGGED_ARMOR_CHESTPLATE = REGISTRY.register("ragged_armor_chestplate", () -> new RaggedArmorItem.Chestplate());
	public static final RegistryObject<Item> RAGGED_ARMOR_LEGGINGS = REGISTRY.register("ragged_armor_leggings", () -> new RaggedArmorItem.Leggings());
	public static final RegistryObject<Item> RAGGED_ARMOR_BOOTS = REGISTRY.register("ragged_armor_boots", () -> new RaggedArmorItem.Boots());
	public static final RegistryObject<Item> TARGET = block(MinecraftAlphaArgModModBlocks.TARGET);
	public static final RegistryObject<Item> LIQUIDFIED_FLAME = REGISTRY.register("liquidfied_flame", () -> new EdibleFireItem());
	public static final RegistryObject<Item> ESSENCE = REGISTRY.register("essence", () -> new EssenceItem());
	public static final RegistryObject<Item> FLAMEBERGE = REGISTRY.register("flameberge", () -> new FlamebergeItem());
	public static final RegistryObject<Item> ASH_GRASS = block(MinecraftAlphaArgModModBlocks.ASH_GRASS);
	public static final RegistryObject<Item> ASH_DIRT = block(MinecraftAlphaArgModModBlocks.ASH_DIRT);
	public static final RegistryObject<Item> YELLOW_GRASS = block(MinecraftAlphaArgModModBlocks.YELLOW_GRASS);
	public static final RegistryObject<Item> GREEN_GRASS = block(MinecraftAlphaArgModModBlocks.GREEN_GRASS);
	public static final RegistryObject<Item> MALACHITE_ORE_1 = block(MinecraftAlphaArgModModBlocks.MALACHITE_ORE_1);
	public static final RegistryObject<Item> PYRITE_ORE_1 = block(MinecraftAlphaArgModModBlocks.PYRITE_ORE_1);
	public static final RegistryObject<Item> CLINOHUMITE_ORE_1 = block(MinecraftAlphaArgModModBlocks.CLINOHUMITE_ORE_1);
	public static final RegistryObject<Item> LACE_AGATE_ORE_1 = block(MinecraftAlphaArgModModBlocks.LACE_AGATE_ORE_1);
	public static final RegistryObject<Item> VENDING_MACHINE_HEALTH_TOP = block(MinecraftAlphaArgModModBlocks.VENDING_MACHINE_HEALTH_TOP);
	public static final RegistryObject<Item> VENDING_MACHINE_HEALTH_BOTTOM = block(MinecraftAlphaArgModModBlocks.VENDING_MACHINE_HEALTH_BOTTOM);
	public static final RegistryObject<Item> VENDING_MACHINE_ARRMOR_TOP = block(MinecraftAlphaArgModModBlocks.VENDING_MACHINE_ARRMOR_TOP);
	public static final RegistryObject<Item> VENDING_MACHINE_ARMOR_BOTTOM = block(MinecraftAlphaArgModModBlocks.VENDING_MACHINE_ARMOR_BOTTOM);
	public static final RegistryObject<Item> VENDING_MACHINE_DASH_TOP = block(MinecraftAlphaArgModModBlocks.VENDING_MACHINE_DASH_TOP);
	public static final RegistryObject<Item> VENDING_MACHINE_DASH_BOTTOM = block(MinecraftAlphaArgModModBlocks.VENDING_MACHINE_DASH_BOTTOM);
	public static final RegistryObject<Item> VENDING_MACHINE_REVIVE_TOP = block(MinecraftAlphaArgModModBlocks.VENDING_MACHINE_REVIVE_TOP);
	public static final RegistryObject<Item> VENDING_MACHINE_REVIVE_BOTTOM = block(MinecraftAlphaArgModModBlocks.VENDING_MACHINE_REVIVE_BOTTOM);
	public static final RegistryObject<Item> WEAPON_UPGRADER = block(MinecraftAlphaArgModModBlocks.WEAPON_UPGRADER);
	public static final RegistryObject<Item> STAIR_LADDER = block(MinecraftAlphaArgModModBlocks.STAIR_LADDER);
	public static final RegistryObject<Item> TRINITY_PLATE = block(MinecraftAlphaArgModModBlocks.TRINITY_PLATE);
	public static final RegistryObject<Item> LOOP_PLATE = block(MinecraftAlphaArgModModBlocks.LOOP_PLATE);
	public static final RegistryObject<Item> SOLAL_PLATE = block(MinecraftAlphaArgModModBlocks.SOLAL_PLATE);
	public static final RegistryObject<Item> ASSOCIATION_PLATE = block(MinecraftAlphaArgModModBlocks.ASSOCIATION_PLATE);
	public static final RegistryObject<Item> DENIAL_PLATE = block(MinecraftAlphaArgModModBlocks.DENIAL_PLATE);
	public static final RegistryObject<Item> DIALECT_PLATE = block(MinecraftAlphaArgModModBlocks.DIALECT_PLATE);
	public static final RegistryObject<Item> MIRRORS_PLATE = block(MinecraftAlphaArgModModBlocks.MIRRORS_PLATE);
	public static final RegistryObject<Item> PART_PLATE = block(MinecraftAlphaArgModModBlocks.PART_PLATE);
	public static final RegistryObject<Item> SWITCH_PLATE = block(MinecraftAlphaArgModModBlocks.SWITCH_PLATE);
	public static final RegistryObject<Item> SYLLABLES_PLATE = block(MinecraftAlphaArgModModBlocks.SYLLABLES_PLATE);
	public static final RegistryObject<Item> OBSERVER_MOB_SPAWN_EGG = REGISTRY.register("observer_mob_spawn_egg", () -> new ForgeSpawnEggItem(MinecraftAlphaArgModModEntities.OBSERVER_MOB, -14145496, -6645094, new Item.Properties()));
	public static final RegistryObject<Item> RECRUITER_SPAWN_EGG = REGISTRY.register("recruiter_spawn_egg", () -> new ForgeSpawnEggItem(MinecraftAlphaArgModModEntities.RECRUITER, -16777216, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> GIANT_SPAWN_EGG = REGISTRY.register("giant_spawn_egg", () -> new ForgeSpawnEggItem(MinecraftAlphaArgModModEntities.GIANT, -16751104, -13408768, new Item.Properties()));
	public static final RegistryObject<Item> ESSENCEFOUNTAIN = block(MinecraftAlphaArgModModBlocks.ESSENCEFOUNTAIN);
	public static final RegistryObject<Item> FRIGID_BITS = REGISTRY.register("frigid_bits", () -> new FrigidBitsItem());
	public static final RegistryObject<Item> HUB_DOOR = doubleBlock(MinecraftAlphaArgModModBlocks.HUB_DOOR);
	public static final RegistryObject<Item> STYLISHARMOR_HELMET = REGISTRY.register("stylisharmor_helmet", () -> new StylisharmorItem.Helmet());
	public static final RegistryObject<Item> STYLISHARMOR_CHESTPLATE = REGISTRY.register("stylisharmor_chestplate", () -> new StylisharmorItem.Chestplate());
	public static final RegistryObject<Item> STYLISHARMOR_LEGGINGS = REGISTRY.register("stylisharmor_leggings", () -> new StylisharmorItem.Leggings());
	public static final RegistryObject<Item> STYLISHARMOR_BOOTS = REGISTRY.register("stylisharmor_boots", () -> new StylisharmorItem.Boots());
	public static final RegistryObject<Item> SUNGLASSES_HELMET = REGISTRY.register("sunglasses_helmet", () -> new SunglassesItem.Helmet());
	public static final RegistryObject<Item> FRYSHROOM = REGISTRY.register("fryshroom", () -> new FryshroomItem());
	public static final RegistryObject<Item> HOURS_LONG_PAST_I = REGISTRY.register("hours_long_past_i", () -> new HoursLongPastIItem());
	public static final RegistryObject<Item> HOURS_LONG_PAST_II = REGISTRY.register("hours_long_past_ii", () -> new HoursLongPastIIItem());
	public static final RegistryObject<Item> HOURS_LONG_PAST_III = REGISTRY.register("hours_long_past_iii", () -> new HoursLongPastIIIItem());
	public static final RegistryObject<Item> HOURS_LONG_PAST_IV = REGISTRY.register("hours_long_past_iv", () -> new HoursLongPastIVItem());
	public static final RegistryObject<Item> THE_ONE_TRUE_BOOK = REGISTRY.register("the_one_true_book", () -> new TheOneTrueBookItem());
	public static final RegistryObject<Item> CANDY_ICE = REGISTRY.register("candy_ice", () -> new CandyIceItem());
	public static final RegistryObject<Item> GRAY_GUN = REGISTRY.register("gray_gun", () -> new GrayGunItem());
	public static final RegistryObject<Item> ERASER = REGISTRY.register("eraser", () -> new EraserItem());
	public static final RegistryObject<Item> RAIN_CONCH = REGISTRY.register("rain_conch", () -> new RainConchItem());
	public static final RegistryObject<Item> DOWNBEAT_UPLINK = REGISTRY.register("downbeat_uplink", () -> new DownbeatUplinkItem());
	public static final RegistryObject<Item> DESAMBRIER = REGISTRY.register("desambrier", () -> new DesambrierItem());
	public static final RegistryObject<Item> GYLDAN_SVERD = REGISTRY.register("gyldan_sverd", () -> new GyldanSverdItem());
	public static final RegistryObject<Item> JUHRY = REGISTRY.register("juhry", () -> new JuhryItem());
	public static final RegistryObject<Item> HIDDENDEN = REGISTRY.register("hiddenden", () -> new HiddendenItem());
	public static final RegistryObject<Item> LEMURIA = REGISTRY.register("lemuria", () -> new LemuriaItem());
	public static final RegistryObject<Item> CONDEMNED = REGISTRY.register("condemned", () -> new CondemnedItem());
	public static final RegistryObject<Item> DIRT = block(MinecraftAlphaArgModModBlocks.DIRT);
	public static final RegistryObject<Item> GRASS_BLOCK = block(MinecraftAlphaArgModModBlocks.GRASS_BLOCK);
	public static final RegistryObject<Item> COBBLESTONE = block(MinecraftAlphaArgModModBlocks.COBBLESTONE);
	public static final RegistryObject<Item> GHOST_BLOCK = block(MinecraftAlphaArgModModBlocks.GHOST_BLOCK);
	public static final RegistryObject<Item> GLOWING_CASE = block(MinecraftAlphaArgModModBlocks.GLOWING_CASE);
	public static final RegistryObject<Item> U_1 = block(MinecraftAlphaArgModModBlocks.U_1);
	public static final RegistryObject<Item> UNUSED_BLOCK_2 = block(MinecraftAlphaArgModModBlocks.UNUSED_BLOCK_2);
	public static final RegistryObject<Item> UNUSED_BLOCK_3 = block(MinecraftAlphaArgModModBlocks.UNUSED_BLOCK_3);
	public static final RegistryObject<Item> UNUSED_BLOCK_4 = block(MinecraftAlphaArgModModBlocks.UNUSED_BLOCK_4);
	public static final RegistryObject<Item> UNUSED_BLOCK_5 = block(MinecraftAlphaArgModModBlocks.UNUSED_BLOCK_5);
	public static final RegistryObject<Item> NO_NAME_BLOCK = block(MinecraftAlphaArgModModBlocks.NO_NAME_BLOCK);
	public static final RegistryObject<Item> UNUSED_BLOCK_6 = block(MinecraftAlphaArgModModBlocks.UNUSED_BLOCK_6);
	public static final RegistryObject<Item> UNUSED_BLOCK_7 = block(MinecraftAlphaArgModModBlocks.UNUSED_BLOCK_7);
	public static final RegistryObject<Item> UNUSED_BLOCK_8 = block(MinecraftAlphaArgModModBlocks.UNUSED_BLOCK_8);
	public static final RegistryObject<Item> UNUSED_BLOCK_9 = block(MinecraftAlphaArgModModBlocks.UNUSED_BLOCK_9);
	public static final RegistryObject<Item> UNUSED_BLOCK_10 = doubleBlock(MinecraftAlphaArgModModBlocks.UNUSED_BLOCK_10);
	public static final RegistryObject<Item> BLACK_GLASS = block(MinecraftAlphaArgModModBlocks.BLACK_GLASS);
	public static final RegistryObject<Item> GREEN_GLASS = block(MinecraftAlphaArgModModBlocks.GREEN_GLASS);
	public static final RegistryObject<Item> MAGENTA_GLASS = block(MinecraftAlphaArgModModBlocks.MAGENTA_GLASS);
	public static final RegistryObject<Item> BLUE_GLASS = block(MinecraftAlphaArgModModBlocks.BLUE_GLASS);
	public static final RegistryObject<Item> CLOTH_PANEL = block(MinecraftAlphaArgModModBlocks.CLOTH_PANEL);
	public static final RegistryObject<Item> BLACK_CLOTH_PANEL = block(MinecraftAlphaArgModModBlocks.BLACK_CLOTH_PANEL);
	public static final RegistryObject<Item> GREEN_CLOTH_PANEL = block(MinecraftAlphaArgModModBlocks.GREEN_CLOTH_PANEL);
	public static final RegistryObject<Item> MAGENTA_CLOTH_PANEL = block(MinecraftAlphaArgModModBlocks.MAGENTA_CLOTH_PANEL);
	public static final RegistryObject<Item> BLUE_CLOTH_PANEL = block(MinecraftAlphaArgModModBlocks.BLUE_CLOTH_PANEL);
	public static final RegistryObject<Item> DEBUG = block(MinecraftAlphaArgModModBlocks.DEBUG);
	public static final RegistryObject<Item> DEBUG_X = block(MinecraftAlphaArgModModBlocks.DEBUG_X);
	public static final RegistryObject<Item> OSLAB = block(MinecraftAlphaArgModModBlocks.OSLAB);
	public static final RegistryObject<Item> UNUSED_BLOCK_11 = block(MinecraftAlphaArgModModBlocks.UNUSED_BLOCK_11);
	public static final RegistryObject<Item> LR_COAL = block(MinecraftAlphaArgModModBlocks.LR_COAL);
	public static final RegistryObject<Item> LR_IRON = block(MinecraftAlphaArgModModBlocks.LR_IRON);
	public static final RegistryObject<Item> LR_GOLD = block(MinecraftAlphaArgModModBlocks.LR_GOLD);
	public static final RegistryObject<Item> LR_DIAMOND = block(MinecraftAlphaArgModModBlocks.LR_DIAMOND);
	public static final RegistryObject<Item> LR_REDSTONE = block(MinecraftAlphaArgModModBlocks.LR_REDSTONE);
	public static final RegistryObject<Item> DEV_1_PLUSHY = block(MinecraftAlphaArgModModBlocks.DEV_1_PLUSHY);
	public static final RegistryObject<Item> BOOKSHELF_ALPHA = block(MinecraftAlphaArgModModBlocks.BOOKSHELF_ALPHA);
	public static final RegistryObject<Item> EMPTY_BOOKSHELF_ALPHA = block(MinecraftAlphaArgModModBlocks.EMPTY_BOOKSHELF_ALPHA);
	public static final RegistryObject<Item> WHITE_GLASS = block(MinecraftAlphaArgModModBlocks.WHITE_GLASS);
	public static final RegistryObject<Item> WOODEN_DOOR = doubleBlock(MinecraftAlphaArgModModBlocks.WOODEN_DOOR);
	public static final RegistryObject<Item> SAND = block(MinecraftAlphaArgModModBlocks.SAND);
	public static final RegistryObject<Item> WOODEN_PLANKS = block(MinecraftAlphaArgModModBlocks.WOODEN_PLANKS);
	public static final RegistryObject<Item> GRAVEL = block(MinecraftAlphaArgModModBlocks.GRAVEL);
	public static final RegistryObject<Item> WOOD = block(MinecraftAlphaArgModModBlocks.WOOD);
	public static final RegistryObject<Item> LEAVES = block(MinecraftAlphaArgModModBlocks.LEAVES);
	public static final RegistryObject<Item> OBSIDIAN = block(MinecraftAlphaArgModModBlocks.OBSIDIAN);
	public static final RegistryObject<Item> WOODEN_STAIRS = block(MinecraftAlphaArgModModBlocks.WOODEN_STAIRS);
	public static final RegistryObject<Item> COBBLESTONE_STAIRS = block(MinecraftAlphaArgModModBlocks.COBBLESTONE_STAIRS);
	public static final RegistryObject<Item> ICE = block(MinecraftAlphaArgModModBlocks.ICE);
	public static final RegistryObject<Item> WORKBENCH = block(MinecraftAlphaArgModModBlocks.WORKBENCH);
	public static final RegistryObject<Item> SNOWY_GRASS_BLOCK = block(MinecraftAlphaArgModModBlocks.SNOWY_GRASS_BLOCK);
	public static final RegistryObject<Item> PEAR = REGISTRY.register("pear", () -> new PearItem());
	public static final RegistryObject<Item> OBSIDIAN_PEAR = REGISTRY.register("obsidian_pear", () -> new ObsidianPearItem());
	public static final RegistryObject<Item> SPEAR = REGISTRY.register("spear", () -> new SpearItem());
	public static final RegistryObject<Item> ESSENCE_RIFLE = REGISTRY.register("essence_rifle", () -> new EssenceRifleItem());
	public static final RegistryObject<Item> GREENSCREENBLOCK = block(MinecraftAlphaArgModModBlocks.GREENSCREENBLOCK);
	public static final RegistryObject<Item> K_2 = REGISTRY.register("k_2", () -> new K2Item());
	public static final RegistryObject<Item> ROCK_BEETLE = REGISTRY.register("rock_beetle", () -> new RockBeetleItem());
	public static final RegistryObject<Item> SANDCASTLES = REGISTRY.register("sandcastles", () -> new SandcastlesItem());
	public static final RegistryObject<Item> ASH_WOOD = block(MinecraftAlphaArgModModBlocks.ASH_WOOD);
	public static final RegistryObject<Item> ASH_LEAVES = block(MinecraftAlphaArgModModBlocks.ASH_LEAVES);
	public static final RegistryObject<Item> ASH_TORCH = block(MinecraftAlphaArgModModBlocks.ASH_TORCH);
	public static final RegistryObject<Item> TERMINAL = block(MinecraftAlphaArgModModBlocks.TERMINAL);
	public static final RegistryObject<Item> NOISE_GEM_TILE = block(MinecraftAlphaArgModModBlocks.NOISE_GEM_TILE);
	public static final RegistryObject<Item> EXPERIMENT_GLASS = block(MinecraftAlphaArgModModBlocks.EXPERIMENT_GLASS);
	public static final RegistryObject<Item> ERROR_CONTAINMENT_BLOCK = block(MinecraftAlphaArgModModBlocks.ERROR_CONTAINMENT_BLOCK);
	public static final RegistryObject<Item> CARD_READER = block(MinecraftAlphaArgModModBlocks.CARD_READER);
	public static final RegistryObject<Item> NOISE_GEM_TILE_STAIRS = block(MinecraftAlphaArgModModBlocks.NOISE_GEM_TILE_STAIRS);
	public static final RegistryObject<Item> NOISE_GEM_TILE_SLAB = block(MinecraftAlphaArgModModBlocks.NOISE_GEM_TILE_SLAB);
	public static final RegistryObject<Item> BRIGHTNESS_BLOCK = block(MinecraftAlphaArgModModBlocks.BRIGHTNESS_BLOCK);
	public static final RegistryObject<Item> BRIGHTNESS_BLOCK_OFF = block(MinecraftAlphaArgModModBlocks.BRIGHTNESS_BLOCK_OFF);
	public static final RegistryObject<Item> FIREWOOD = block(MinecraftAlphaArgModModBlocks.FIREWOOD);
	public static final RegistryObject<Item> FIREWOOD_LEAVES = block(MinecraftAlphaArgModModBlocks.FIREWOOD_LEAVES);
	public static final RegistryObject<Item> FIREWOOD_PLANKS = block(MinecraftAlphaArgModModBlocks.FIREWOOD_PLANKS);
	public static final RegistryObject<Item> COMPACTED_CELESTIAL_FLAME = block(MinecraftAlphaArgModModBlocks.COMPACTED_CELESTIAL_FLAME);
	public static final RegistryObject<Item> STONE_BRICKS = block(MinecraftAlphaArgModModBlocks.STONE_BRICKS);
	public static final RegistryObject<Item> INFUSED_BRICKS = block(MinecraftAlphaArgModModBlocks.INFUSED_BRICKS);
	public static final RegistryObject<Item> INFUSED_COBBLESTONE = block(MinecraftAlphaArgModModBlocks.INFUSED_COBBLESTONE);
	public static final RegistryObject<Item> INFUSED_STONE = block(MinecraftAlphaArgModModBlocks.INFUSED_STONE);
	public static final RegistryObject<Item> SMOOTH_STONE_F = block(MinecraftAlphaArgModModBlocks.SMOOTH_STONE_F);
	public static final RegistryObject<Item> SMOOTH_INFUSED_STONE = block(MinecraftAlphaArgModModBlocks.SMOOTH_INFUSED_STONE);
	public static final RegistryObject<Item> WIREFRAME = block(MinecraftAlphaArgModModBlocks.WIREFRAME);
	public static final RegistryObject<Item> COBBLESTONE_FANCE = block(MinecraftAlphaArgModModBlocks.COBBLESTONE_FANCE);
	public static final RegistryObject<Item> INFUSED_COBBLESTONE_FANCE = block(MinecraftAlphaArgModModBlocks.INFUSED_COBBLESTONE_FANCE);
	public static final RegistryObject<Item> STORE_BLOCK_1_F = block(MinecraftAlphaArgModModBlocks.STORE_BLOCK_1_F);
	public static final RegistryObject<Item> STORE_BLOCK_2_F = block(MinecraftAlphaArgModModBlocks.STORE_BLOCK_2_F);
	public static final RegistryObject<Item> FIREWOOD_DOOR_F = doubleBlock(MinecraftAlphaArgModModBlocks.FIREWOOD_DOOR_F);
	public static final RegistryObject<Item> VENDING_MACHINE_SHOP = block(MinecraftAlphaArgModModBlocks.VENDING_MACHINE_SHOP);
	public static final RegistryObject<Item> VENDING_MACHINE_SHOP_2 = block(MinecraftAlphaArgModModBlocks.VENDING_MACHINE_SHOP_2);
	public static final RegistryObject<Item> ALPHAVER_LOGO = block(MinecraftAlphaArgModModBlocks.ALPHAVER_LOGO);
	public static final RegistryObject<Item> MESH_BLOCK_DOWN = block(MinecraftAlphaArgModModBlocks.MESH_BLOCK_DOWN);
	public static final RegistryObject<Item> MESH_BLOCK_UP = block(MinecraftAlphaArgModModBlocks.MESH_BLOCK_UP);
	public static final RegistryObject<Item> ADMIN_COLUMN = block(MinecraftAlphaArgModModBlocks.ADMIN_COLUMN);
	public static final RegistryObject<Item> ADMIN_SPACE_FLOOR_TILE = block(MinecraftAlphaArgModModBlocks.ADMIN_SPACE_FLOOR_TILE);
	public static final RegistryObject<Item> ADMIN_SPACE_GLASS = block(MinecraftAlphaArgModModBlocks.ADMIN_SPACE_GLASS);
	public static final RegistryObject<Item> ADMIN_TECH = block(MinecraftAlphaArgModModBlocks.ADMIN_TECH);
	public static final RegistryObject<Item> ADMIN_TERMINAL = block(MinecraftAlphaArgModModBlocks.ADMIN_TERMINAL);
	public static final RegistryObject<Item> KEY_SLOTTER = block(MinecraftAlphaArgModModBlocks.KEY_SLOTTER);
	public static final RegistryObject<Item> MOJANG_BLOCK = block(MinecraftAlphaArgModModBlocks.MOJANG_BLOCK);
	public static final RegistryObject<Item> PSI_MONITOR = block(MinecraftAlphaArgModModBlocks.PSI_MONITOR);
	public static final RegistryObject<Item> SERVER_CONTAINERS = block(MinecraftAlphaArgModModBlocks.SERVER_CONTAINERS);
	public static final RegistryObject<Item> SERVER_COOLING_FAN = block(MinecraftAlphaArgModModBlocks.SERVER_COOLING_FAN);
	public static final RegistryObject<Item> STAR_MONITOR = block(MinecraftAlphaArgModModBlocks.STAR_MONITOR);
	public static final RegistryObject<Item> X_MONITOR = block(MinecraftAlphaArgModModBlocks.X_MONITOR);
	public static final RegistryObject<Item> Y_MONITOR = block(MinecraftAlphaArgModModBlocks.Y_MONITOR);
	public static final RegistryObject<Item> VOID_KEY = REGISTRY.register("void_key", () -> new VoidKeyItem());
	public static final RegistryObject<Item> MONITOR = block(MinecraftAlphaArgModModBlocks.MONITOR);
	public static final RegistryObject<Item> MOON_BLOCK_1 = block(MinecraftAlphaArgModModBlocks.MOON_BLOCK_1);
	public static final RegistryObject<Item> MOON_BLOCK_2 = block(MinecraftAlphaArgModModBlocks.MOON_BLOCK_2);
	public static final RegistryObject<Item> MOON_BLOCK_3 = block(MinecraftAlphaArgModModBlocks.MOON_BLOCK_3);
	public static final RegistryObject<Item> MOON_BLOCK_4 = block(MinecraftAlphaArgModModBlocks.MOON_BLOCK_4);
	public static final RegistryObject<Item> MOON_BLOCK_5 = block(MinecraftAlphaArgModModBlocks.MOON_BLOCK_5);
	public static final RegistryObject<Item> MOON_BLOCK_6 = block(MinecraftAlphaArgModModBlocks.MOON_BLOCK_6);
	public static final RegistryObject<Item> CORRUPTED_CARD_READER = block(MinecraftAlphaArgModModBlocks.CORRUPTED_CARD_READER);
	public static final RegistryObject<Item> WALL_1 = block(MinecraftAlphaArgModModBlocks.WALL_1);
	public static final RegistryObject<Item> WALL_2 = block(MinecraftAlphaArgModModBlocks.WALL_2);
	public static final RegistryObject<Item> WALL_3 = block(MinecraftAlphaArgModModBlocks.WALL_3);
	public static final RegistryObject<Item> WALL_4 = block(MinecraftAlphaArgModModBlocks.WALL_4);
	public static final RegistryObject<Item> WALL_5 = block(MinecraftAlphaArgModModBlocks.WALL_5);
	public static final RegistryObject<Item> MOON_BLOCK = block(MinecraftAlphaArgModModBlocks.MOON_BLOCK);
	public static final RegistryObject<Item> NOISE_GEM_WALL = block(MinecraftAlphaArgModModBlocks.NOISE_GEM_WALL);
	public static final RegistryObject<Item> SUN_BLOCK = block(MinecraftAlphaArgModModBlocks.SUN_BLOCK);
	public static final RegistryObject<Item> ADMIN_SPACE_FLOOR = block(MinecraftAlphaArgModModBlocks.ADMIN_SPACE_FLOOR);
	public static final RegistryObject<Item> CORRIDOR_EXPOSED_PIPES = block(MinecraftAlphaArgModModBlocks.CORRIDOR_EXPOSED_PIPES);
	public static final RegistryObject<Item> CORRIDOR_LANTERN = block(MinecraftAlphaArgModModBlocks.CORRIDOR_LANTERN);
	public static final RegistryObject<Item> CORRIDOR_LIGHT = block(MinecraftAlphaArgModModBlocks.CORRIDOR_LIGHT);
	public static final RegistryObject<Item> CORRIDOR_MACHINERY = block(MinecraftAlphaArgModModBlocks.CORRIDOR_MACHINERY);
	public static final RegistryObject<Item> CORRIDOR_NETTING = block(MinecraftAlphaArgModModBlocks.CORRIDOR_NETTING);
	public static final RegistryObject<Item> CORRIDOR_PILLAR = block(MinecraftAlphaArgModModBlocks.CORRIDOR_PILLAR);
	public static final RegistryObject<Item> CORRIDOR_SMOOTH = block(MinecraftAlphaArgModModBlocks.CORRIDOR_SMOOTH);
	public static final RegistryObject<Item> CORRIDOR_RAILING = block(MinecraftAlphaArgModModBlocks.CORRIDOR_RAILING);
	public static final RegistryObject<Item> CORRIDOR_SUPPORTS = block(MinecraftAlphaArgModModBlocks.CORRIDOR_SUPPORTS);
	public static final RegistryObject<Item> CORRIDOR_TILED_PIPES = block(MinecraftAlphaArgModModBlocks.CORRIDOR_TILED_PIPES);
	public static final RegistryObject<Item> CORRIDOR_TRACKS = block(MinecraftAlphaArgModModBlocks.CORRIDOR_TRACKS);
	public static final RegistryObject<Item> DELTA_END_SKY = block(MinecraftAlphaArgModModBlocks.DELTA_END_SKY);
	public static final RegistryObject<Item> DELTA_END_STONE = block(MinecraftAlphaArgModModBlocks.DELTA_END_STONE);
	public static final RegistryObject<Item> ASSETSTILESACCEPT = REGISTRY.register("assetstilesaccept", () -> new AssetstilesacceptItem());
	public static final RegistryObject<Item> ASSETSTILESDENY = REGISTRY.register("assetstilesdeny", () -> new AssetstilesdenyItem());
	public static final RegistryObject<Item> EXPERIMENT_GLASS_PANE = block(MinecraftAlphaArgModModBlocks.EXPERIMENT_GLASS_PANE);
	public static final RegistryObject<Item> JAR = block(MinecraftAlphaArgModModBlocks.JAR);
	public static final RegistryObject<Item> VOID_GEM = REGISTRY.register("void_gem", () -> new VoidGemItem());
	public static final RegistryObject<Item> VOID_GEM_ORE = block(MinecraftAlphaArgModModBlocks.VOID_GEM_ORE);
	public static final RegistryObject<Item> DISMANTLER = REGISTRY.register("dismantler", () -> new DismantlerItem());
	public static final RegistryObject<Item> CREEPERS_HEART = block(MinecraftAlphaArgModModBlocks.CREEPERS_HEART);
	public static final RegistryObject<Item> LIVING_VOID_BLOCK = block(MinecraftAlphaArgModModBlocks.LIVING_VOID_BLOCK);
	public static final RegistryObject<Item> SHELVE = block(MinecraftAlphaArgModModBlocks.SHELVE);
	public static final RegistryObject<Item> MUSIC_PLAYER = block(MinecraftAlphaArgModModBlocks.MUSIC_PLAYER);
	public static final RegistryObject<Item> SQUIRMING_ORGANISM = block(MinecraftAlphaArgModModBlocks.SQUIRMING_ORGANISM);
	public static final RegistryObject<Item> MELTED_VOID_BEING_ROCK = block(MinecraftAlphaArgModModBlocks.MELTED_VOID_BEING_ROCK);
	public static final RegistryObject<Item> HELL_BULB = block(MinecraftAlphaArgModModBlocks.HELL_BULB);
	public static final RegistryObject<Item> TBOTV_BRICKS = block(MinecraftAlphaArgModModBlocks.TBOTV_BRICKS);
	public static final RegistryObject<Item> SERVER_DRIVE = REGISTRY.register("server_drive", () -> new ServerDriveItem());
	public static final RegistryObject<Item> ORGANISM = block(MinecraftAlphaArgModModBlocks.ORGANISM);
	public static final RegistryObject<Item> MINESWEEPER_BLOCK = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_BLOCK);
	public static final RegistryObject<Item> MINESWEEPER_1 = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_1);
	public static final RegistryObject<Item> MINESWEEPER_2 = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_2);
	public static final RegistryObject<Item> MINESWEEPER_3 = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_3);
	public static final RegistryObject<Item> MINESWEEPER_4 = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_4);
	public static final RegistryObject<Item> MINESWEEPER_5 = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_5);
	public static final RegistryObject<Item> MINESWEEPER_6 = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_6);
	public static final RegistryObject<Item> MINESWEEPER_7 = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_7);
	public static final RegistryObject<Item> MINESWEEPER_8 = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_8);
	public static final RegistryObject<Item> MINESWEEPER_EMPTY = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_EMPTY);
	public static final RegistryObject<Item> MINESWEEPER_MINE = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_MINE);
	public static final RegistryObject<Item> MINESWEEPER_TRIGGERED_MINE = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_TRIGGERED_MINE);
	public static final RegistryObject<Item> ERROR_BLOCK = block(MinecraftAlphaArgModModBlocks.ERROR_BLOCK);
	public static final RegistryObject<Item> MINEWATCH_CAMERA_2 = block(MinecraftAlphaArgModModBlocks.MINEWATCH_CAMERA_2);
	public static final RegistryObject<Item> MINEWATCH_CAMERA_1 = block(MinecraftAlphaArgModModBlocks.MINEWATCH_CAMERA_1);
	public static final RegistryObject<Item> MINESWEEPER_FLAG = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_FLAG);
	public static final RegistryObject<Item> MINESWEEPER_CROSSED_MINE = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_CROSSED_MINE);
	public static final RegistryObject<Item> MINESWEEPER_QUESTIONMARK_BUTTON = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_QUESTIONMARK_BUTTON);
	public static final RegistryObject<Item> MINESWEEPER_QUESTIONMARK = block(MinecraftAlphaArgModModBlocks.MINESWEEPER_QUESTIONMARK);
	public static final RegistryObject<Item> DEBUG_BLOCK = block(MinecraftAlphaArgModModBlocks.DEBUG_BLOCK);
	public static final RegistryObject<Item> DEBUG_BLOCK_1 = block(MinecraftAlphaArgModModBlocks.DEBUG_BLOCK_1);
	public static final RegistryObject<Item> TILE_1 = block(MinecraftAlphaArgModModBlocks.TILE_1);
	public static final RegistryObject<Item> TILE_2 = block(MinecraftAlphaArgModModBlocks.TILE_2);
	public static final RegistryObject<Item> TILE_3 = block(MinecraftAlphaArgModModBlocks.TILE_3);
	public static final RegistryObject<Item> TILE_4 = block(MinecraftAlphaArgModModBlocks.TILE_4);
	public static final RegistryObject<Item> TILE_5 = block(MinecraftAlphaArgModModBlocks.TILE_5);
	public static final RegistryObject<Item> TILE_6 = block(MinecraftAlphaArgModModBlocks.TILE_6);
	public static final RegistryObject<Item> TILE_7 = block(MinecraftAlphaArgModModBlocks.TILE_7);
	public static final RegistryObject<Item> KEYCARD = REGISTRY.register("keycard", () -> new KeycardItem());
	public static final RegistryObject<Item> TERREN_BLOCK = block(MinecraftAlphaArgModModBlocks.TERREN_BLOCK);
	public static final RegistryObject<Item> BUGNATION_PLUSHIE = block(MinecraftAlphaArgModModBlocks.BUGNATION_PLUSHIE);
	public static final RegistryObject<Item> STAR_PLUSHIE = block(MinecraftAlphaArgModModBlocks.STAR_PLUSHIE);
	public static final RegistryObject<Item> AUTHOR_PLUSHIE = block(MinecraftAlphaArgModModBlocks.AUTHOR_PLUSHIE);
	public static final RegistryObject<Item> ANDREWGAMING67_PLUSHIE = block(MinecraftAlphaArgModModBlocks.ANDREWGAMING67_PLUSHIE);
	public static final RegistryObject<Item> VOID_VINE = block(MinecraftAlphaArgModModBlocks.VOID_VINE);
	public static final RegistryObject<Item> DYLANDOMINECRAFT_PLUSHIE = block(MinecraftAlphaArgModModBlocks.DYLANDOMINECRAFT_PLUSHIE);
	public static final RegistryObject<Item> TBOTV_BRICKS_SLAB = block(MinecraftAlphaArgModModBlocks.TBOTV_BRICKS_SLAB);
	public static final RegistryObject<Item> RUBY_ORE = block(MinecraftAlphaArgModModBlocks.RUBY_ORE);
	public static final RegistryObject<Item> RUBY_SOULER = block(MinecraftAlphaArgModModBlocks.RUBY_SOULER);
	public static final RegistryObject<Item> IRON_SOULER = block(MinecraftAlphaArgModModBlocks.IRON_SOULER);
	public static final RegistryObject<Item> GOLD_SOULER = block(MinecraftAlphaArgModModBlocks.GOLD_SOULER);
	public static final RegistryObject<Item> PORTAL_DISABLED = block(MinecraftAlphaArgModModBlocks.PORTAL_DISABLED);
	public static final RegistryObject<Item> PORTAL_ENABLED = block(MinecraftAlphaArgModModBlocks.PORTAL_ENABLED);
	public static final RegistryObject<Item> PORTAL_RESTRICTED = block(MinecraftAlphaArgModModBlocks.PORTAL_RESTRICTED);
	public static final RegistryObject<Item> AMONG_US_TNT = block(MinecraftAlphaArgModModBlocks.AMONG_US_TNT);
	public static final RegistryObject<Item> RUBY_BLOCK = block(MinecraftAlphaArgModModBlocks.RUBY_BLOCK);
	public static final RegistryObject<Item> QRST_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.QRST_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> ABCD_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.ABCD_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> EFGH_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.EFGH_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> IJKL_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.IJKL_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> MNOP_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.MNOP_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> UVWX_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.UVWX_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> YZ_01_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.YZ_01_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> COMMUNICATION_BLOCK_2345 = block(MinecraftAlphaArgModModBlocks.COMMUNICATION_BLOCK_2345);
	public static final RegistryObject<Item> COMMUNICATION_BLOCK_6789 = block(MinecraftAlphaArgModModBlocks.COMMUNICATION_BLOCK_6789);
	public static final RegistryObject<Item> BLUE_GRAY_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.BLUE_GRAY_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> GRAY_RED_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.GRAY_RED_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> CAPS_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.CAPS_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> HAPPY_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.HAPPY_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> SAD_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.SAD_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> GREEN_BLUE_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.GREEN_BLUE_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> RED_GREEN_COMMUNICATION_BLOCK = block(MinecraftAlphaArgModModBlocks.RED_GREEN_COMMUNICATION_BLOCK);
	public static final RegistryObject<Item> SOUL_PLUSHIE = block(MinecraftAlphaArgModModBlocks.SOUL_PLUSHIE);
	public static final RegistryObject<Item> HALF_SOUL_PLUSHIE = block(MinecraftAlphaArgModModBlocks.HALF_SOUL_PLUSHIE);
	public static final RegistryObject<Item> AMONG_US_BOOKSHELF = block(MinecraftAlphaArgModModBlocks.AMONG_US_BOOKSHELF);
	public static final RegistryObject<Item> AMONG_US_LEAVES = block(MinecraftAlphaArgModModBlocks.AMONG_US_LEAVES);
	public static final RegistryObject<Item> SOUL_BOOKSHELF = block(MinecraftAlphaArgModModBlocks.SOUL_BOOKSHELF);
	public static final RegistryObject<Item> SOUL_BRICKS = block(MinecraftAlphaArgModModBlocks.SOUL_BRICKS);
	public static final RegistryObject<Item> SOUL_COAL_ORE = block(MinecraftAlphaArgModModBlocks.SOUL_COAL_ORE);
	public static final RegistryObject<Item> SOUL_COBBLESTONE = block(MinecraftAlphaArgModModBlocks.SOUL_COBBLESTONE);
	public static final RegistryObject<Item> SOUL_STONE = block(MinecraftAlphaArgModModBlocks.SOUL_STONE);
	public static final RegistryObject<Item> SOUL_DIRT = block(MinecraftAlphaArgModModBlocks.SOUL_DIRT);
	public static final RegistryObject<Item> SOUL_GRASS = block(MinecraftAlphaArgModModBlocks.SOUL_GRASS);
	public static final RegistryObject<Item> SOUL_GOLD_BLOCK = block(MinecraftAlphaArgModModBlocks.SOUL_GOLD_BLOCK);
	public static final RegistryObject<Item> SOUL_GOLD_ORE = block(MinecraftAlphaArgModModBlocks.SOUL_GOLD_ORE);
	public static final RegistryObject<Item> SOUL_IRON_BLOCK = block(MinecraftAlphaArgModModBlocks.SOUL_IRON_BLOCK);
	public static final RegistryObject<Item> SOUL_IRON_ORE = block(MinecraftAlphaArgModModBlocks.SOUL_IRON_ORE);
	public static final RegistryObject<Item> SOUL_WOOD = block(MinecraftAlphaArgModModBlocks.SOUL_WOOD);
	public static final RegistryObject<Item> SOUL_PLANK = block(MinecraftAlphaArgModModBlocks.SOUL_PLANK);
	public static final RegistryObject<Item> SOUL_LEAVES = block(MinecraftAlphaArgModModBlocks.SOUL_LEAVES);
	public static final RegistryObject<Item> SOUL_OBSIDIAN = block(MinecraftAlphaArgModModBlocks.SOUL_OBSIDIAN);
	public static final RegistryObject<Item> SOUL_SAND = block(MinecraftAlphaArgModModBlocks.SOUL_SAND);
	public static final RegistryObject<Item> SOUL_TNT = block(MinecraftAlphaArgModModBlocks.SOUL_TNT);
	public static final RegistryObject<Item> SOUL_GRAVEL = block(MinecraftAlphaArgModModBlocks.SOUL_GRAVEL);
	public static final RegistryObject<Item> SOUL_SPONGE = block(MinecraftAlphaArgModModBlocks.SOUL_SPONGE);
	public static final RegistryObject<Item> SOUL_MOSSY_COBBLESTONE = block(MinecraftAlphaArgModModBlocks.SOUL_MOSSY_COBBLESTONE);
	public static final RegistryObject<Item> DEAD_ROSE = block(MinecraftAlphaArgModModBlocks.DEAD_ROSE);
	public static final RegistryObject<Item> SOUL_ENTITY_SPAWN_EGG = REGISTRY.register("soul_entity_spawn_egg", () -> new ForgeSpawnEggItem(MinecraftAlphaArgModModEntities.SOUL_ENTITY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> ENTITY_SPAWN_EGG = REGISTRY.register("entity_spawn_egg", () -> new ForgeSpawnEggItem(MinecraftAlphaArgModModEntities.ENTITY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SOUL_WORKBENCH = block(MinecraftAlphaArgModModBlocks.SOUL_WORKBENCH);
	public static final RegistryObject<Item> AUTHENTICATOR = block(MinecraftAlphaArgModModBlocks.AUTHENTICATOR);
	public static final RegistryObject<Item> MOJANG_LOGO_BLOCK = block(MinecraftAlphaArgModModBlocks.MOJANG_LOGO_BLOCK);
	public static final RegistryObject<Item> EMPTY_LOGO_BLOCK = block(MinecraftAlphaArgModModBlocks.EMPTY_LOGO_BLOCK);
	public static final RegistryObject<Item> BRICK_WALL = block(MinecraftAlphaArgModModBlocks.BRICK_WALL);
	public static final RegistryObject<Item> WINDOW = block(MinecraftAlphaArgModModBlocks.WINDOW);
	public static final RegistryObject<Item> FLOOR_TILES = block(MinecraftAlphaArgModModBlocks.FLOOR_TILES);
	public static final RegistryObject<Item> RED_MOJANG_LOGO_BLOCK = block(MinecraftAlphaArgModModBlocks.RED_MOJANG_LOGO_BLOCK);
	public static final RegistryObject<Item> PURPLE_PILLAR = block(MinecraftAlphaArgModModBlocks.PURPLE_PILLAR);
	public static final RegistryObject<Item> RED_PILLAR = block(MinecraftAlphaArgModModBlocks.RED_PILLAR);
	public static final RegistryObject<Item> TILE_SLAB = block(MinecraftAlphaArgModModBlocks.TILE_SLAB);
	public static final RegistryObject<Item> TILE_STAIRS = block(MinecraftAlphaArgModModBlocks.TILE_STAIRS);
	public static final RegistryObject<Item> BRICK_WALL_STAIRS = block(MinecraftAlphaArgModModBlocks.BRICK_WALL_STAIRS);
	public static final RegistryObject<Item> BRICK_WALL_SLAB = block(MinecraftAlphaArgModModBlocks.BRICK_WALL_SLAB);
	public static final RegistryObject<Item> TOWER_TRANSPORTER = block(MinecraftAlphaArgModModBlocks.TOWER_TRANSPORTER);
	public static final RegistryObject<Item> OBSIDIAN_FORGE = block(MinecraftAlphaArgModModBlocks.OBSIDIAN_FORGE);
	public static final RegistryObject<Item> AFLITE_ORE = block(MinecraftAlphaArgModModBlocks.AFLITE_ORE);
	public static final RegistryObject<Item> IKEN_LEAVES = block(MinecraftAlphaArgModModBlocks.IKEN_LEAVES);
	public static final RegistryObject<Item> IKEN_LOG = block(MinecraftAlphaArgModModBlocks.IKEN_LOG);
	public static final RegistryObject<Item> IKEN_PLANKS = block(MinecraftAlphaArgModModBlocks.IKEN_PLANKS);
	public static final RegistryObject<Item> INFUSED_AFLITE_ORE = block(MinecraftAlphaArgModModBlocks.INFUSED_AFLITE_ORE);
	public static final RegistryObject<Item> SOUL_CAGE_EMPTY = block(MinecraftAlphaArgModModBlocks.SOUL_CAGE_EMPTY);
	public static final RegistryObject<Item> SOUL_CAGE_FULL = block(MinecraftAlphaArgModModBlocks.SOUL_CAGE_FULL);
	public static final RegistryObject<Item> NEW_BISMUTH_ORE = block(MinecraftAlphaArgModModBlocks.NEW_BISMUTH_ORE);
	public static final RegistryObject<Item> RUBY = REGISTRY.register("ruby", () -> new RubyItem());
	public static final RegistryObject<Item> NEW_PYRITE_ORE = block(MinecraftAlphaArgModModBlocks.NEW_PYRITE_ORE);
	public static final RegistryObject<Item> NEW_CLINOHUMITE_ORE = block(MinecraftAlphaArgModModBlocks.NEW_CLINOHUMITE_ORE);
	public static final RegistryObject<Item> NEW_LACE_AGATE_ORE = block(MinecraftAlphaArgModModBlocks.NEW_LACE_AGATE_ORE);
	public static final RegistryObject<Item> NEW_MALACHITE_ORE = block(MinecraftAlphaArgModModBlocks.NEW_MALACHITE_ORE);
	public static final RegistryObject<Item> TBOTV_TROPHY = block(MinecraftAlphaArgModModBlocks.TBOTV_TROPHY);
	public static final RegistryObject<Item> CLASSIC_MINECRAFT_TROPHY = block(MinecraftAlphaArgModModBlocks.CLASSIC_MINECRAFT_TROPHY);
	public static final RegistryObject<Item> MWD = block(MinecraftAlphaArgModModBlocks.MWD);
	public static final RegistryObject<Item> MINE_WATCH_TROPHY = block(MinecraftAlphaArgModModBlocks.MINE_WATCH_TROPHY);
	public static final RegistryObject<Item> UNKNOWN = block(MinecraftAlphaArgModModBlocks.UNKNOWN);
	public static final RegistryObject<Item> UNKNOWN_2 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_2);
	public static final RegistryObject<Item> UNKNOWN_3 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_3);
	public static final RegistryObject<Item> UNKNOWN_4 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_4);
	public static final RegistryObject<Item> UNKNOWN_5 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_5);
	public static final RegistryObject<Item> UNKNOWN_6 = doubleBlock(MinecraftAlphaArgModModBlocks.UNKNOWN_6);
	public static final RegistryObject<Item> UNKNOWN_7 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_7);
	public static final RegistryObject<Item> UNKNOWN_8 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_8);
	public static final RegistryObject<Item> UNKNOWN_9 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_9);
	public static final RegistryObject<Item> UNKNOWN_10 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_10);
	public static final RegistryObject<Item> UNKNOWN_11 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_11);
	public static final RegistryObject<Item> UNKNOWN_12 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_12);
	public static final RegistryObject<Item> UNKNOWN_13 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_13);
	public static final RegistryObject<Item> UNKNOWN_14 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_14);
	public static final RegistryObject<Item> UNKNOWN_15 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_15);
	public static final RegistryObject<Item> PILLARG = block(MinecraftAlphaArgModModBlocks.PILLARG);
	public static final RegistryObject<Item> WALLG = block(MinecraftAlphaArgModModBlocks.WALLG);
	public static final RegistryObject<Item> WALLGP = block(MinecraftAlphaArgModModBlocks.WALLGP);
	public static final RegistryObject<Item> CEILING_LAMP = block(MinecraftAlphaArgModModBlocks.CEILING_LAMP);
	public static final RegistryObject<Item> CEILING_TILE = block(MinecraftAlphaArgModModBlocks.CEILING_TILE);
	public static final RegistryObject<Item> FLOORCARPET = block(MinecraftAlphaArgModModBlocks.FLOORCARPET);
	public static final RegistryObject<Item> FLOOR_CARPET_STAIRS = block(MinecraftAlphaArgModModBlocks.FLOOR_CARPET_STAIRS);
	public static final RegistryObject<Item> FLOOR_CARPET_SLAB = block(MinecraftAlphaArgModModBlocks.FLOOR_CARPET_SLAB);
	public static final RegistryObject<Item> FLOOR_NONCARPET_HARD = block(MinecraftAlphaArgModModBlocks.FLOOR_NONCARPET_HARD);
	public static final RegistryObject<Item> DOOR_1 = doubleBlock(MinecraftAlphaArgModModBlocks.DOOR_1);
	public static final RegistryObject<Item> UNKNOWN_16 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_16);
	public static final RegistryObject<Item> UNKNOWN_17 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_17);
	public static final RegistryObject<Item> UNKNOWN_18 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_18);
	public static final RegistryObject<Item> UNKNOWN_19 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_19);
	public static final RegistryObject<Item> UNKNOWN_20 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_20);
	public static final RegistryObject<Item> UNKNOWN_21 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_21);
	public static final RegistryObject<Item> CAT_THEME = REGISTRY.register("cat_theme", () -> new CatThemeItem());
	public static final RegistryObject<Item> UNKNOWN_22 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_22);
	public static final RegistryObject<Item> UNKNOWN_23 = block(MinecraftAlphaArgModModBlocks.UNKNOWN_23);
	public static final RegistryObject<Item> DBG_SPAWN_EGG = REGISTRY.register("dbg_spawn_egg", () -> new ForgeSpawnEggItem(MinecraftAlphaArgModModEntities.DBG, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> DARK_WOOD = block(MinecraftAlphaArgModModBlocks.DARK_WOOD);
	public static final RegistryObject<Item> DARK_PLANKS = block(MinecraftAlphaArgModModBlocks.DARK_PLANKS);
	public static final RegistryObject<Item> DARK_BRICKS = block(MinecraftAlphaArgModModBlocks.DARK_BRICKS);
	public static final RegistryObject<Item> DARK_DOOR = doubleBlock(MinecraftAlphaArgModModBlocks.DARK_DOOR);
	public static final RegistryObject<Item> DARK_LEAVES = block(MinecraftAlphaArgModModBlocks.DARK_LEAVES);
	public static final RegistryObject<Item> DARK_SAPLING = block(MinecraftAlphaArgModModBlocks.DARK_SAPLING);
	public static final RegistryObject<Item> HUB_TILE_BLOCK = block(MinecraftAlphaArgModModBlocks.HUB_TILE_BLOCK);
	public static final RegistryObject<Item> HUB_WALL_BLOCK = block(MinecraftAlphaArgModModBlocks.HUB_WALL_BLOCK);
	public static final RegistryObject<Item> HUB_GLASS_BLOCK = block(MinecraftAlphaArgModModBlocks.HUB_GLASS_BLOCK);
	public static final RegistryObject<Item> GOLDEN_APPLE_BLOCK = block(MinecraftAlphaArgModModBlocks.GOLDEN_APPLE_BLOCK);
	public static final RegistryObject<Item> IDK_SOMETHINGCOOL = block(MinecraftAlphaArgModModBlocks.IDK_SOMETHINGCOOL);
	public static final RegistryObject<Item> BLUE_GIANT_SPAWN_EGG = REGISTRY.register("blue_giant_spawn_egg", () -> new ForgeSpawnEggItem(MinecraftAlphaArgModModEntities.BLUE_GIANT, -6710785, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> ARRIVAL = REGISTRY.register("arrival", () -> new ArrivalItem());
	public static final RegistryObject<Item> UNUSED_1 = block(MinecraftAlphaArgModModBlocks.UNUSED_1);
	public static final RegistryObject<Item> UNUSED_2 = block(MinecraftAlphaArgModModBlocks.UNUSED_2);
	public static final RegistryObject<Item> UNUSED_3 = block(MinecraftAlphaArgModModBlocks.UNUSED_3);
	public static final RegistryObject<Item> UNUSED_4 = block(MinecraftAlphaArgModModBlocks.UNUSED_4);
	public static final RegistryObject<Item> UNUSED_5 = block(MinecraftAlphaArgModModBlocks.UNUSED_5);
	public static final RegistryObject<Item> UNUSED_6 = block(MinecraftAlphaArgModModBlocks.UNUSED_6);
	public static final RegistryObject<Item> UNUSED_ITEM = REGISTRY.register("unused_item", () -> new UnusedItemItem());
	public static final RegistryObject<Item> UNUSED_ITEM_1 = REGISTRY.register("unused_item_1", () -> new UnusedItem1Item());
	public static final RegistryObject<Item> UNUSED_ITEM_2 = REGISTRY.register("unused_item_2", () -> new UnusedItem2Item());
	public static final RegistryObject<Item> UNUSED_ITEM_3 = REGISTRY.register("unused_item_3", () -> new UnusedItem3Item());
	public static final RegistryObject<Item> UNUSED_ITEM_4 = REGISTRY.register("unused_item_4", () -> new UnusedItem4Item());
	public static final RegistryObject<Item> UNUSED_ITEM_5 = REGISTRY.register("unused_item_5", () -> new UnusedItem5Item());
	public static final RegistryObject<Item> UNUSED_ITEM_6 = REGISTRY.register("unused_item_6", () -> new UnusedItem6Item());
	public static final RegistryObject<Item> UNUSED_ITEM_7 = REGISTRY.register("unused_item_7", () -> new UnusedItem7Item());
	public static final RegistryObject<Item> UNUSED_ITEM_8 = REGISTRY.register("unused_item_8", () -> new UnusedItem8Item());
	public static final RegistryObject<Item> UNUSED_ITEM_9 = REGISTRY.register("unused_item_9", () -> new UnusedItem9Item());
	public static final RegistryObject<Item> UNUSED_ITEM_10 = REGISTRY.register("unused_item_10", () -> new UnusedItem10Item());
	public static final RegistryObject<Item> UNUSED_TOOL = REGISTRY.register("unused_tool", () -> new UnusedToolItem());
	public static final RegistryObject<Item> UNUSED_TOOL_1 = REGISTRY.register("unused_tool_1", () -> new UnusedTool1Item());
	public static final RegistryObject<Item> UNUSED_TOOL_3 = REGISTRY.register("unused_tool_3", () -> new UnusedTool3Item());
	public static final RegistryObject<Item> UNUSED_TOOL_2 = REGISTRY.register("unused_tool_2", () -> new UnusedTool2Item());
	public static final RegistryObject<Item> UNUSED_TOOL_4 = REGISTRY.register("unused_tool_4", () -> new UnusedTool4Item());
	public static final RegistryObject<Item> UNUSED_TOOL_5 = REGISTRY.register("unused_tool_5", () -> new UnusedTool5Item());
	public static final RegistryObject<Item> UNUSED_TOOL_6 = REGISTRY.register("unused_tool_6", () -> new UnusedTool6Item());
	public static final RegistryObject<Item> UNUSED_TOOL_7 = REGISTRY.register("unused_tool_7", () -> new UnusedTool7Item());
	public static final RegistryObject<Item> UNUSED_TOOL_8 = REGISTRY.register("unused_tool_8", () -> new UnusedTool8Item());
	public static final RegistryObject<Item> UNUSED_TOOL_9 = REGISTRY.register("unused_tool_9", () -> new UnusedTool9Item());
	public static final RegistryObject<Item> UNUSED_TOOL_10 = REGISTRY.register("unused_tool_10", () -> new UnusedTool10Item());
	public static final RegistryObject<Item> UNUSED_TOOL_11 = REGISTRY.register("unused_tool_11", () -> new UnusedTool11Item());
	public static final RegistryObject<Item> HUB_SMOOTH_STONE_SLAB = block(MinecraftAlphaArgModModBlocks.HUB_SMOOTH_STONE_SLAB);
	public static final RegistryObject<Item> HUB_PLANKS = block(MinecraftAlphaArgModModBlocks.HUB_PLANKS);
	public static final RegistryObject<Item> HUB_BRICKS = block(MinecraftAlphaArgModModBlocks.HUB_BRICKS);
	public static final RegistryObject<Item> OTHER_JUKEBOX = block(MinecraftAlphaArgModModBlocks.OTHER_JUKEBOX);
	public static final RegistryObject<Item> HUB_MOJANG_BLOCK = block(MinecraftAlphaArgModModBlocks.HUB_MOJANG_BLOCK);
	public static final RegistryObject<Item> HUB_MOJANG_BLOCK_1 = block(MinecraftAlphaArgModModBlocks.HUB_MOJANG_BLOCK_1);
	public static final RegistryObject<Item> HUB_MOJANG_BLOCK_2 = block(MinecraftAlphaArgModModBlocks.HUB_MOJANG_BLOCK_2);
	public static final RegistryObject<Item> HUB_HUB_TILE = block(MinecraftAlphaArgModModBlocks.HUB_HUB_TILE);
	public static final RegistryObject<Item> HUB_PILLAR = block(MinecraftAlphaArgModModBlocks.HUB_PILLAR);
	public static final RegistryObject<Item> HUB_GLASS = block(MinecraftAlphaArgModModBlocks.HUB_GLASS);
	public static final RegistryObject<Item> HUB_SLATE_BEACON = block(MinecraftAlphaArgModModBlocks.HUB_SLATE_BEACON);
	public static final RegistryObject<Item> HUB_SLATE_PILLAR = block(MinecraftAlphaArgModModBlocks.HUB_SLATE_PILLAR);
	public static final RegistryObject<Item> HUB_FAKE_SAND = block(MinecraftAlphaArgModModBlocks.HUB_FAKE_SAND);
	public static final RegistryObject<Item> HUB_FAKE_STONE = block(MinecraftAlphaArgModModBlocks.HUB_FAKE_STONE);
	public static final RegistryObject<Item> HUB_SLATE_BRICKS = block(MinecraftAlphaArgModModBlocks.HUB_SLATE_BRICKS);
	public static final RegistryObject<Item> HUB_TILE = block(MinecraftAlphaArgModModBlocks.HUB_TILE);
	public static final RegistryObject<Item> HUB_STONE_TILE = block(MinecraftAlphaArgModModBlocks.HUB_STONE_TILE);
	public static final RegistryObject<Item> HUB_WALL = block(MinecraftAlphaArgModModBlocks.HUB_WALL);
	public static final RegistryObject<Item> HUB_TILE_YELLOW = block(MinecraftAlphaArgModModBlocks.HUB_TILE_YELLOW);
	public static final RegistryObject<Item> HUB_TILE_BLUE = block(MinecraftAlphaArgModModBlocks.HUB_TILE_BLUE);
	public static final RegistryObject<Item> HUB_HIGHWOOD_LOG = block(MinecraftAlphaArgModModBlocks.HUB_HIGHWOOD_LOG);
	public static final RegistryObject<Item> HUB_HIGHWOOD_LEAVES = block(MinecraftAlphaArgModModBlocks.HUB_HIGHWOOD_LEAVES);
	public static final RegistryObject<Item> ASH_GRASS_1 = block(MinecraftAlphaArgModModBlocks.ASH_GRASS_1);
	public static final RegistryObject<Item> HUB_FAKE_GRASS = block(MinecraftAlphaArgModModBlocks.HUB_FAKE_GRASS);
	public static final RegistryObject<Item> HUB_FAKE_DIRT = block(MinecraftAlphaArgModModBlocks.HUB_FAKE_DIRT);
	public static final RegistryObject<Item> HUB_ASH_BLOCK_2 = block(MinecraftAlphaArgModModBlocks.HUB_ASH_BLOCK_2);
	public static final RegistryObject<Item> HUB_HIGHWOOD_ROOTS = block(MinecraftAlphaArgModModBlocks.HUB_HIGHWOOD_ROOTS);
	public static final RegistryObject<Item> IDKSK = block(MinecraftAlphaArgModModBlocks.IDKSK);
	public static final RegistryObject<Item> BREDAS = block(MinecraftAlphaArgModModBlocks.BREDAS);
	public static final RegistryObject<Item> ARG_FANS = block(MinecraftAlphaArgModModBlocks.ARG_FANS);
	public static final RegistryObject<Item> CLAYMORES = block(MinecraftAlphaArgModModBlocks.CLAYMORES);
	public static final RegistryObject<Item> CUBE_OF_HEAVEN = block(MinecraftAlphaArgModModBlocks.CUBE_OF_HEAVEN);
	public static final RegistryObject<Item> MICHIGAN = block(MinecraftAlphaArgModModBlocks.MICHIGAN);
	public static final RegistryObject<Item> INFINITIES = block(MinecraftAlphaArgModModBlocks.INFINITIES);
	public static final RegistryObject<Item> INTEGRITIE_CUBE = block(MinecraftAlphaArgModModBlocks.INTEGRITIE_CUBE);
	public static final RegistryObject<Item> CAT_CUBE = block(MinecraftAlphaArgModModBlocks.CAT_CUBE);
	public static final RegistryObject<Item> VINNY = block(MinecraftAlphaArgModModBlocks.VINNY);
	public static final RegistryObject<Item> NONE = block(MinecraftAlphaArgModModBlocks.NONE);
	public static final RegistryObject<Item> ME_CAT_CUBE = block(MinecraftAlphaArgModModBlocks.ME_CAT_CUBE);
	public static final RegistryObject<Item> WE_CAT_CUBE = block(MinecraftAlphaArgModModBlocks.WE_CAT_CUBE);
	public static final RegistryObject<Item> PURPUR_BRICKS = block(MinecraftAlphaArgModModBlocks.PURPUR_BRICKS);
	public static final RegistryObject<Item> REALITYSPACE_ARROW_BLOCK = block(MinecraftAlphaArgModModBlocks.REALITYSPACE_ARROW_BLOCK);
	public static final RegistryObject<Item> REALITYSPACE_MS_PACMAN_BLOCK = block(MinecraftAlphaArgModModBlocks.REALITYSPACE_MS_PACMAN_BLOCK);
	public static final RegistryObject<Item> REALITYSPACE_PATTERN_BLOCK = block(MinecraftAlphaArgModModBlocks.REALITYSPACE_PATTERN_BLOCK);
	public static final RegistryObject<Item> REALITYSPACE_TILE_BLOCK = block(MinecraftAlphaArgModModBlocks.REALITYSPACE_TILE_BLOCK);
	public static final RegistryObject<Item> REALITYSPACE_CROSS_BLOCK = block(MinecraftAlphaArgModModBlocks.REALITYSPACE_CROSS_BLOCK);
	public static final RegistryObject<Item> HALLOWED_BRICKS = block(MinecraftAlphaArgModModBlocks.HALLOWED_BRICKS);
	public static final RegistryObject<Item> HALLOWED_BRICKS_SLAB = block(MinecraftAlphaArgModModBlocks.HALLOWED_BRICKS_SLAB);
	public static final RegistryObject<Item> HALLOWED_BRICKS_STAIRS = block(MinecraftAlphaArgModModBlocks.HALLOWED_BRICKS_STAIRS);
	public static final RegistryObject<Item> HALLOWED_STONE = block(MinecraftAlphaArgModModBlocks.HALLOWED_STONE);
	public static final RegistryObject<Item> HALLOWED_PILLAR = block(MinecraftAlphaArgModModBlocks.HALLOWED_PILLAR);
	public static final RegistryObject<Item> CHISELED_HALLOWED_STONE = block(MinecraftAlphaArgModModBlocks.CHISELED_HALLOWED_STONE);
	public static final RegistryObject<Item> COMPRESSED_RIFT = block(MinecraftAlphaArgModModBlocks.COMPRESSED_RIFT);
	public static final RegistryObject<Item> COMPRESSED_STATIC = block(MinecraftAlphaArgModModBlocks.COMPRESSED_STATIC);
	public static final RegistryObject<Item> COMPRESSED_STATIC_PORTAL = block(MinecraftAlphaArgModModBlocks.COMPRESSED_STATIC_PORTAL);
	public static final RegistryObject<Item> DEFECTED_WOOD = block(MinecraftAlphaArgModModBlocks.DEFECTED_WOOD);
	public static final RegistryObject<Item> FRACTURED_INFLUENCE = block(MinecraftAlphaArgModModBlocks.FRACTURED_INFLUENCE);
	public static final RegistryObject<Item> FRACTURED_MIST = block(MinecraftAlphaArgModModBlocks.FRACTURED_MIST);
	public static final RegistryObject<Item> DIMINISH_FLOWER = block(MinecraftAlphaArgModModBlocks.DIMINISH_FLOWER);
	public static final RegistryObject<Item> BRIXGOA_SPAWN_EGG = REGISTRY.register("brixgoa_spawn_egg", () -> new ForgeSpawnEggItem(MinecraftAlphaArgModModEntities.BRIXGOA, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> QUANTUM_BLOCK = block(MinecraftAlphaArgModModBlocks.QUANTUM_BLOCK);
	public static final RegistryObject<Item> PERLIN_GEM = block(MinecraftAlphaArgModModBlocks.PERLIN_GEM);
	public static final RegistryObject<Item> PERLIN_LIGHT = block(MinecraftAlphaArgModModBlocks.PERLIN_LIGHT);
	public static final RegistryObject<Item> PERLIN_DBG = block(MinecraftAlphaArgModModBlocks.PERLIN_DBG);
	public static final RegistryObject<Item> PERLIN_STAIRS = block(MinecraftAlphaArgModModBlocks.PERLIN_STAIRS);
	public static final RegistryObject<Item> MONITOR_BLOCK = block(MinecraftAlphaArgModModBlocks.MONITOR_BLOCK);
	public static final RegistryObject<Item> PERLIN_DARK = block(MinecraftAlphaArgModModBlocks.PERLIN_DARK);
	public static final RegistryObject<Item> PERLIN_DARK_STAR = block(MinecraftAlphaArgModModBlocks.PERLIN_DARK_STAR);
	public static final RegistryObject<Item> PERLIN_ADMINSPACE = block(MinecraftAlphaArgModModBlocks.PERLIN_ADMINSPACE);
	public static final RegistryObject<Item> PERLINE_RED_BLOCK = block(MinecraftAlphaArgModModBlocks.PERLINE_RED_BLOCK);
	public static final RegistryObject<Item> PERLIN_KEYBLOCK = block(MinecraftAlphaArgModModBlocks.PERLIN_KEYBLOCK);
	public static final RegistryObject<Item> PERLIN_BLUE_STAR = block(MinecraftAlphaArgModModBlocks.PERLIN_BLUE_STAR);
	public static final RegistryObject<Item> PERLINE_BLUE_BLOCK = block(MinecraftAlphaArgModModBlocks.PERLINE_BLUE_BLOCK);
	public static final RegistryObject<Item> PERLIN_DBG_BLUE_STAR = block(MinecraftAlphaArgModModBlocks.PERLIN_DBG_BLUE_STAR);
	public static final RegistryObject<Item> PERLIN_DBG_BLUE_LINE = block(MinecraftAlphaArgModModBlocks.PERLIN_DBG_BLUE_LINE);
	public static final RegistryObject<Item> PERLIN_DBG_RED_STAR = block(MinecraftAlphaArgModModBlocks.PERLIN_DBG_RED_STAR);
	public static final RegistryObject<Item> PERLIN_DBG_RED_LINE = block(MinecraftAlphaArgModModBlocks.PERLIN_DBG_RED_LINE);
	public static final RegistryObject<Item> KEY_DJ = REGISTRY.register("key_dj", () -> new KeyDJItem());
	public static final RegistryObject<Item> JUMPGRADE = REGISTRY.register("jumpgrade", () -> new JumpgradeItem());
	public static final RegistryObject<Item> EXCHANGER = REGISTRY.register("exchanger", () -> new ExchangerItem());
	public static final RegistryObject<Item> DATA_DAISY = block(MinecraftAlphaArgModModBlocks.DATA_DAISY);
	public static final RegistryObject<Item> NOISE_SUP = REGISTRY.register("noise_sup", () -> new NoiseSupItem());
	public static final RegistryObject<Item> QUEST_GIVER = block(MinecraftAlphaArgModModBlocks.QUEST_GIVER);
	public static final RegistryObject<Item> QUEST_MANAGER = REGISTRY.register("quest_manager", () -> new QuestMenagerItem());
	public static final RegistryObject<Item> FF_33D_5 = block(MinecraftAlphaArgModModBlocks.FF_33D_5);
	public static final RegistryObject<Item> DEV_PROMO = REGISTRY.register("dev_promo", () -> new DevPromoItem());
	public static final RegistryObject<Item> SLAIZE_00 = block(MinecraftAlphaArgModModBlocks.SLAIZE_00);
	public static final RegistryObject<Item> SLAIZE_10 = block(MinecraftAlphaArgModModBlocks.SLAIZE_10);
	public static final RegistryObject<Item> SLAIZE_20 = block(MinecraftAlphaArgModModBlocks.SLAIZE_20);
	public static final RegistryObject<Item> SLAIZE_30 = block(MinecraftAlphaArgModModBlocks.SLAIZE_30);
	public static final RegistryObject<Item> SLAIZE_40 = block(MinecraftAlphaArgModModBlocks.SLAIZE_40);
	public static final RegistryObject<Item> SLAIZE_50 = block(MinecraftAlphaArgModModBlocks.SLAIZE_50);
	public static final RegistryObject<Item> SLAIZE_60 = block(MinecraftAlphaArgModModBlocks.SLAIZE_60);
	public static final RegistryObject<Item> SLAIZE_70 = block(MinecraftAlphaArgModModBlocks.SLAIZE_70);
	public static final RegistryObject<Item> SLAIZE_80 = block(MinecraftAlphaArgModModBlocks.SLAIZE_80);
	public static final RegistryObject<Item> SLAIZE_90 = block(MinecraftAlphaArgModModBlocks.SLAIZE_90);
	public static final RegistryObject<Item> SLAIZE_100 = block(MinecraftAlphaArgModModBlocks.SLAIZE_100);
	public static final RegistryObject<Item> SLAIZE_110 = block(MinecraftAlphaArgModModBlocks.SLAIZE_110);
	public static final RegistryObject<Item> SLAIZE_120 = block(MinecraftAlphaArgModModBlocks.SLAIZE_120);
	public static final RegistryObject<Item> SLAIZE_130 = block(MinecraftAlphaArgModModBlocks.SLAIZE_130);
	public static final RegistryObject<Item> SLAIZE_140 = block(MinecraftAlphaArgModModBlocks.SLAIZE_140);
	public static final RegistryObject<Item> SLAIZE_150 = block(MinecraftAlphaArgModModBlocks.SLAIZE_150);
	public static final RegistryObject<Item> SLAIZE_160 = block(MinecraftAlphaArgModModBlocks.SLAIZE_160);
	public static final RegistryObject<Item> SLAIZE_170 = block(MinecraftAlphaArgModModBlocks.SLAIZE_170);
	public static final RegistryObject<Item> SLAIZE_180 = block(MinecraftAlphaArgModModBlocks.SLAIZE_180);
	public static final RegistryObject<Item> SLAIZE_190 = block(MinecraftAlphaArgModModBlocks.SLAIZE_190);
	public static final RegistryObject<Item> SLAIZE_200 = block(MinecraftAlphaArgModModBlocks.SLAIZE_200);
	public static final RegistryObject<Item> SLAIZE_210 = block(MinecraftAlphaArgModModBlocks.SLAIZE_210);
	public static final RegistryObject<Item> SLAIZE_220 = block(MinecraftAlphaArgModModBlocks.SLAIZE_220);
	public static final RegistryObject<Item> SLAIZE_230 = block(MinecraftAlphaArgModModBlocks.SLAIZE_230);
	public static final RegistryObject<Item> SLAIZE_240 = block(MinecraftAlphaArgModModBlocks.SLAIZE_240);
	public static final RegistryObject<Item> SLAIZE_250 = block(MinecraftAlphaArgModModBlocks.SLAIZE_250);
	public static final RegistryObject<Item> SLAIZE_260 = block(MinecraftAlphaArgModModBlocks.SLAIZE_260);
	public static final RegistryObject<Item> SLAIZE_270 = block(MinecraftAlphaArgModModBlocks.SLAIZE_270);
	public static final RegistryObject<Item> SLAIZE_280 = block(MinecraftAlphaArgModModBlocks.SLAIZE_280);
	public static final RegistryObject<Item> SLAIZE_290 = block(MinecraftAlphaArgModModBlocks.SLAIZE_290);
	public static final RegistryObject<Item> JAMES_22_PLUSHIE = block(MinecraftAlphaArgModModBlocks.JAMES_22_PLUSHIE);
	public static final RegistryObject<Item> SCYTHE = REGISTRY.register("scythe", () -> new ScytheItem());
	public static final RegistryObject<Item> DEVELOPER_PORTAL = block(MinecraftAlphaArgModModBlocks.DEVELOPER_PORTAL);
	public static final RegistryObject<Item> CHECKERBOARD = block(MinecraftAlphaArgModModBlocks.CHECKERBOARD);
	public static final RegistryObject<Item> CHECKERBOARD_STAIRS = block(MinecraftAlphaArgModModBlocks.CHECKERBOARD_STAIRS);
	public static final RegistryObject<Item> LILYPAD_112 = block(MinecraftAlphaArgModModBlocks.LILYPAD_112);
	public static final RegistryObject<Item> LILYPAD_1121 = block(MinecraftAlphaArgModModBlocks.LILYPAD_1121);
	public static final RegistryObject<Item> LILYPAD_1122 = block(MinecraftAlphaArgModModBlocks.LILYPAD_1122);
	public static final RegistryObject<Item> LILYPAD_1123 = block(MinecraftAlphaArgModModBlocks.LILYPAD_1123);
	public static final RegistryObject<Item> STEVEN_SPAWN_EGG = REGISTRY.register("steven_spawn_egg", () -> new ForgeSpawnEggItem(MinecraftAlphaArgModModEntities.STEVEN, -16737895, -2711704, new Item.Properties()));

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
